services:
  - type: web
    name: projeto01
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"